#!/usr/bin/env bash
# A file that installs nginx on my web server

sudo apt-get -y update

sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
# Restart Nginx to apply changes
sudo service nginx restart