#!/usr/bin/env bash
# A file that installs nginx on my web server

sudo apt-get -y update

sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

sudo bash -c 'cat <<EOF > /etc/nginx/nginx.conf
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location / {
        return 200 "<html><body><h1>Hello World!</h1></body></html>";
    }
}
EOF'

# Restart Nginx to apply changes
sudo service nginx restart