#!/usr/bin/env bash
# Configure Nginx so that its HTTP response

# Install nginx on your web-01

# Update package information then install Nginx
server_name=$(hostname)
sudo apt-get -y update
sudo apt-get -y install nginx

# enabe the most restrictive profile that will allow the traffic
sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une error_page" > /usr/share/nginx/html/custom_404.html
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;

    # Add index.php to the list if you are using PHP
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        # First attempt to serve request as file, then
        # as a directory, then fall back to displaying a 404.
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        root /var/www/html;
        internal;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=3lFkDc6dFoY;
    }

    add_header X-Served-By $server_name;
}
" > /etc/nginx/sites-enabled/default

sudo systemctl restart nginx
