#!/usr/bin/env bash
# Install nginx on your web-01

# Update package information then install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Enable the most restrictive profile that will allow the traffic
sudo ufw allow 'Nginx HTTP'

# Pass the content
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# Start Nginx
sudo service nginx start

# Redirect
new_content="rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"

# Use a more specific sed command to replace the desired location
if ! grep -e "rewrite ^/redirect_me" /etc/nginx/sites-available/default
then
	sudo sed -i "/server_name _;/a $new_content" /etc/nginx/sites-available/default
fi

# Customize the 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

new_error="listen 80 default_server;\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
if ! grep -e "error_page 404 /404_not_found.html" /etc/nginx/sites-available/default
then
	sudo sed -i "/listen 80 default_server;/c $new_error" /etc/nginx/sites-available/default
fi
# add  a custom header http
if ! grep -e "add_header X-Served-By" /etc/nginx/sites-enabled/default
then
        sudo sed -i "/server_name _;/a \ \ \ \ \ \ \ \ add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
fi
# Test Nginx configuration and restart
sudo nginx -t && sudo service nginx restart
