#!/usr/bin/env bash
# Install and configure HAproxy on Ib-01

sudo apt-get -y update
sudo apt-get -y install haproxy

# Make a backup of the configuration file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Open the configuration file
sudo nano /etc/haproxy/haproxy.cfg

server_config=\
"
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 151666-web-01 18.214.87.3:80 check
    server 151666-web-02 54.237.61.25:80 check
"
# shellcheck disable=SC2154
echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

echo "configured - Roundrobin On web-01 & web-02"

if [ "$(pgrep -c haproxy)" -le 0 ]; then
	sudo service haproxy start
else
	sudo service haproxy restart
fi
