#!/usr/bin/env bash
# Install and configure HAproxy on Ib-01

sudo apt-get -y update
sudo apt-get -y install haproxy

# Make a backup of the configuration file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Open the configuration file
sudo nano /etc/haproxy/haproxy.cfg

server_config=\
"
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend http_front
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server 151666-web-01 18.214.87.3:80 check
    server 151666-web-02 54.237.61.25:80 check
"
sudo systemctl enable haproxy
sudo systemctl restart haproxy
