#!/usr/bin/env bash
# A Bash script that stops 4-to_infinity_and_beyond process.
file="7-highlander"
process_name=$(pgrep -f "$file")
if [ -n "$highlander_pid" ]; then    
    pkill -15 "$process_name"
fi