#!/usr/bin/env bash
# A Bash script that stops 4-to_infinity_and_beyond process.
file="7-highlander"
process_name=$(pgrep -f "$file")
sleep 5
if [ -n "$file" ];
then
    kill -15 "$process_name"
    echo "I am invincible!!!"
fi
