#!/usr/bin/env bash
# A Bash script that displays numbers from 1 to 100.
param=101
s=1
while [ "$s" -ne "$param" ];
do
    if [ $((s % 3)) -eq 0 ] && [ $((s % 5)) -eq 0 ]; then
    echo "FizzBuzz"
    elif [ $((s % 3)) -eq 0 ]; then
    echo "Fizz"
    elif [ $((s % 5)) -eq 0 ]; then
    echo "Buzz"
    else
    echo "$s"
    fi
    ((s++))    
done
