#!/usr/bin/env bash
# A Bash script that loops from 1 to 10 and:
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations
v=1
y=11
text="Best School"
while [ $v -ne $y ]
do    
    if [ $v -eq 4 ];then
    echo "bad luck";
    elif [ $v -eq 8 ];then
    echo "good luck"
    else
    echo "$text"
    fi
    ((v++))
done