#!/usr/bin/env bash
# A Bash script that displays numbers from 1 to 20 and:
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration
v=1
y=21
while [ $v -ne $y ]
do    
    if [ $v -eq 4 ];then
    echo "bad luck from China"
    elif [ $v -eq 9 ];then
    echo "bad luck from Japan"
    elif [ $v -eq 17 ];then
    echo "bad luck from Italy"
    else
    echo $v
    fi

    ((v++))
done