#!/usr/bin/env bash
# A Bash script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59
H=0
E=13
while [ $H -ne $E ]
do
    echo "Hour: $H"
    M=1
    EM=60
    while [ $M -ne $EM ]
    do 
        echo "$M"
        ((m++))
    done

    ((H++))
done
    

