#!/usr/bin/env bash
# A Bash script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59
H=0
while [ $H -ne 13 ]; do
    echo "Hour: $H"
    
    M=1    
    while [ $M -ne 60 ]; do 
        echo "$M"
        ((m++))
    done

    ((H++))
done
    

