#!/usr/bin/env bash
# A Bash script that gives you information about the school file.
file=school
for file in *; do
    if find . -name "$file" -quit; then   
        echo "$file file exists"
    else
        echo "$file file does not exist"
    fi
    
    if [ "$(head -n 1 "$file" | wc -l)" -ne 0 ]; then
        echo "$file file is not empty"
    else
        echo "$file file is empty"
    fi
    if [ -f "$file" ]; then
        echo "$file is a regular file"   
    fi   
done