#!/usr/bin/env bash

server {
    listen 80 default_server;
    listen      [::]:80 default_server ipv6only=on;
    server_name 54.162.82.148; # Replace with your public IP or domain name
    add_header  X-Served-By 277540-web-01;

    location /airbnb-onepage/ {
        proxy_pass http://localhost:5000/airbnb-onepage/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        return 404;
    }
}
